
version: "3"
services:

  arcadedb:
    image: arcadedata/arcadedb:23.7.1
    container_name: md-arcadedb
    ports:
      - 2480:2480
    environment:
      - JAVA_OPTS=-Darcadedb.server.rootPassword=node_master
    volumes:
      - arcadedata_md:/home/arcadedb/databases

  nats-jetstreams:
    image: nats:2.10.22-linux
    container_name: md-nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    restart: unless-stopped
    command: ["-js", "-m", "8222"]

  solr:
    image: solr:9.7
    container_name: md-solr
    ports:
      - 8983:8983
    restart: unless-stopped
    volumes:
      - solrdata_md:/var/solr
    command: ["solr-precreate", "messydesk"]


volumes:
  arcadedata_md: {}
  solrdata_md: {}

